### ISSUE TITLE
API endpoint not found: pylon/datasift

### ISSUE THREAD

**Issue by stenpiren** [haganbt/pepp#113]
I tried compile the file ```CMA_topic_analysis.js``` and I got the CSV files generated but without data. The terminal windows shows: ```ERROR pepp: MESSAGE: API endpoint not found.```

Any alternative to get the data in the CSV files? I would like to check the tableau story with these data, for learning purposes. Any help?

**Comment by haganbt** [comment]
The PYLON product from DataSift is no longer available and hence the API no longer exists. I will archive this project so its clear to others.
