### ISSUE TITLE
Custom nested with only one tag in tagTree do not create key value in output

### ISSUE THREAD

**Issue by deannomuraatdatasift** [haganbt/pepp#72]
(Tested with BA_brand_reputation_management.js config)

If there is only a single tag in a tagTree, custom nested queries do not create a key value for that tag in the output csv. For example timeSeries_by_entity, language_by_entity, etc.

Native child queries are fine as are any with 2+ tag values.

Tried adding a dummy tag to the filter to have a second value but it appears if the result is empty for that second tag the behavior doesn't change.

**Comment by haganbt** [comment]
For any custom nested, if the parent request only returns a single value, the parent data is never merged with the result:

```{
        "index": "fb",
        "target": "fb.author.gender",
        "threshold": 1,
        "then": {
          "target": "fb.type",
          "threshold": 2
        }
      }
```

This is because the cache object is never collected. Further investigation needed.

**Comment by haganbt** [comment]
@deannomuraatdatasift This is fixed in [v2](https://github.com/haganbt/pepp/tree/async-api) (async task api). Feel free to try this branch out but keep in mind its changing daily.
