### ISSUE TITLE
Revise console view for task based API

### ISSUE THREAD

**Issue by samaybar** [haganbt/pepp#87]
In the console, might it be nice to differentiate between the requests being made to start tasks versus the requests being made to get data? (both in terms of the count and the way they are displayed) It would make it much easier to see how many tasks have been started, versus just showing the total number of API requests, which lumps apples and oranges together.

**Comment by haganbt** [comment]
Yes agreed @samaybar - definitely a good addition. I will get it added.

**Comment by haganbt** [comment]
Closed via f7b92dd07b0131037e90c1fbf70317ac87919547
