### ISSUE TITLE
Improved timeseries extraction

### ISSUE THREAD

**Issue by erwanlenagard** [haganbt/pepp#90]
Hi Ben !

Would it be possible to implement nested queries to extract timeseries ? For instance, i would like to extract actions by age and gender over time. I didn't found any easy way to write this kind of query. It seems I need to write multiple queries using filters and merge them.

==> such kind of nested query could be more efficient ?
```json
{
	"name": "actions_gender_age",
	"target": "fb.type",
	"threshold": 4,
	"child": {
			"target": "fb.author.gender",
			"threshold": 2,
			"child": {
				"target": "fb.author.age",
				"threshold": 6,
				"then": {
				"analysis_type": "timeSeries",
				"interval": "day"
			}
	}
}
},
```
		
Thanks for your help ! :)

**Comment by haganbt** [comment]
@erwanlenagard If I understand correctly you want to run a freqDist for each result of a timeSeries or visa versa. If that is the case, you can simply overwrite the nested type of query using the ```analysis_type``` key. Appreciate this could be documented better.

Make sure you are running the [latest](https://github.com/haganbt/pepp#sync-new-changes) version.

Heres an example. To get the age gender breakdown by day:

```json
    "timeSeries": [
      {
        "interval": "day",
        "then": {
          "analysis_type": "freqDist",
          "target": "fb.parent.author.gender",
          "threshold": 2,
          "child": {
            "target": "fb.parent.author.age",
            "threshold": 6
          }
        }
      }
    ]
```
