### ISSUE TITLE
Filters should be able to be set at the index level

### ISSUE THREAD

**Issue by samaybar** [haganbt/pepp#92]
When defining an index in PEPP, it would be very helpful to be able to define a filter to be inherited by all queries using that index. This is especially valuable if you are trying to exclude noise from an index with a filter, but using baselining in the index -- you would want to add a filter for all "default" index tasks, but not for the baseline ones. Thus, a global filter would be too much, and having to add the filter to every task is inconvenient.

**Comment by haganbt** [comment]
closing as duplicate of #49
